Add "arena history" , "Set profile pic" , "Set privacy" translate.
simplicialsoftware/nebulous-translations pull request #234
Opened 2024-08-24 21:15 UTC by chan084

ID : 18613714

2024-08-24 22:16 UTC, Jeii20 requested changes
These texts you mentioned are already in file and already translated.

`ARENA HISTORY`: located at line 747
`SET PROFILE PIC`: located at line 993
`SET PRIVACY`: located at line 1113

Please never add new strings without basing on the `res/values` (English file) first.

2024-08-24 22:26 UTC, closed without merging

2024-08-25 01:11 UTC, chan084 commented
What words are not translated?

2024년 8월 25일 (일) 오전 7:26, Jeii20 ***@***.***>님이 작성:

> Closed #234
> <https://github.com/simplicialsoftware/nebulous-translations/pull/234>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/simplicialsoftware/nebulous-translations/pull/234#event-14002540228>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKWA3BCTQKDFAZUT2JVKQ7TZTECBBAVCNFSM6AAAAABNB45VOSVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUGAYDENJUGAZDEOA>
> .
> You are receiving this because you authored the thread.Message ID:
> <simplicialsoftware/nebulous-translations/pull/234/issue_event/14002540228
> @github.com>
>

2024-08-25 02:11 UTC, chan084 commented
몇 개 더 추가로 번역하여 보냈습니다

2024년 8월 25일 (일) 오전 10:11, 김민찬 ***@***.***>님이 작성:

> What words are not translated?
>
> 2024년 8월 25일 (일) 오전 7:26, Jeii20 ***@***.***>님이 작성:
>
>> Closed #234
>> <https://github.com/simplicialsoftware/nebulous-translations/pull/234>.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/simplicialsoftware/nebulous-translations/pull/234#event-14002540228>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BKWA3BCTQKDFAZUT2JVKQ7TZTECBBAVCNFSM6AAAAABNB45VOSVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUGAYDENJUGAZDEOA>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> <simplicialsoftware/nebulous-translations/pull/234/issue_event/14002540228
>> @github.com>
>>
>

2024-08-25 02:12 UTC, chan084 commented
I translated a few more and sent them.

2024년 8월 25일 (일) 오전 11:11, 김민찬 ***@***.***>님이 작성:

> 몇 개 더 추가로 번역하여 보냈습니다
>
> 2024년 8월 25일 (일) 오전 10:11, 김민찬 ***@***.***>님이 작성:
>
>> What words are not translated?
>>
>> 2024년 8월 25일 (일) 오전 7:26, Jeii20 ***@***.***>님이 작성:
>>
>>> Closed #234
>>> <https://github.com/simplicialsoftware/nebulous-translations/pull/234>.
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/simplicialsoftware/nebulous-translations/pull/234#event-14002540228>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/BKWA3BCTQKDFAZUT2JVKQ7TZTECBBAVCNFSM6AAAAABNB45VOSVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUGAYDENJUGAZDEOA>
>>> .
>>> You are receiving this because you authored the thread.Message ID:
>>> <simplicialsoftware/nebulous-translations/pull/234/issue_event/14002540228
>>> @github.com>
>>>
>>