res/values-b+es+r419
simplicialsoftware/nebulous-translations pull request #31
Opened 2024-08-12 18:09 UTC by Banned44nebu

Tradução do "pm" para o espanhol.

2024-08-12 18:57 UTC, CritiKangel requested changes
"PM" comes from "PRIVATE MESSAGE", which translates to "MENSAJE PRIVADO"; the translation, if any, should be "MP"

2024-08-12 19:01 UTC, Banned44nebu commented
Ok, muito obrigado por me avisar!

Em seg., 12 de ago. de 2024 15:57, Ángel K ***@***.***>
escreveu:

> ***@***.**** requested changes on this pull request.
>
> "PM" comes from "PRIVATE MESSAGE", which translates to "MENSAJE PRIVADO";
> the translation, if any, should be "MP"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/simplicialsoftware/nebulous-translations/pull/31#pullrequestreview-2233804128>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKOMEVN2RGQHMCBLFBXG3UDZREASFAVCNFSM6AAAAABMMVR3S2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMZTHAYDIMJSHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> .com>
>

2024-08-12 19:13 UTC, closed without merging

2024-08-13 16:39 UTC, CritiKangel commented on res/values-b+es+r419/strings.xml
> +    <string name="pm">priv</string>
This should be MP

2024-08-13 16:39 UTC, CritiKangel commented on res/values-b+es+r419/strings.xml
>      <string name="You_are_already_friends_">You are already friends.</string>
Not translated.

2024-08-13 16:39 UTC, CritiKangel commented on res/values-b+es+r419/strings.xml
>      <string name="Account_must_be_1_day_old_to_send_mail_">Account must be 1 day old to send mail.</string>
Not translated.

2024-08-13 16:39 UTC, CritiKangel commented on res/values-b+es+r419/strings.xml
>  Si no deseas registrarte, aún puedes jugar en modo individual."
European Spanish, not LATAM Spanish.