Update portuguese Brazill (PT-BR)
simplicialsoftware/nebulous-translations pull request #546
Opened 2024-09-02 23:03 UTC by V104-byte

Grammatical errors corrected and some texts changed for better understanding in Portuguese Brazil

Others:

MY id in Nebulous (31016893)

2024-09-03 11:47 UTC, AssaNebulous reviewed
Hi, I don't think such a change is necessary.
Por favor desconsidere.

2024-09-04 10:36 UTC, Jeii20 requested changes

2024-09-04 10:36 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Spectating">"Espectar um Jogador"</string>
Previous translation was correct

2024-09-04 10:36 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="No_such_clan_exists_">"Este clã não existe."</string>
Previous translation was correct

2024-09-04 10:36 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Min_Players">"Mínimo de Jogadores"</string>
Lines 71 and 72:

Please keep the abbreviations like it is in English (blue colour)

2024-09-04 10:36 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Max_People">"Limite de Pessoas"</string>
Please keep the abbreviation here; previous translation was correct

2024-09-04 10:36 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Send_Message">"Enviar Uma Mensagem"</string>
Line 454: Previous translation was correct
Line 455: Inserting "uma" will make the string length too long. Previous translation was correct

2024-09-04 10:36 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="ArenaDescription">Você terá apenas uma vida. O vencedor receberá %s plasma. Negociar vitórias ou "pontos gratuitos" resultará em banimento.</string>
Previous translation was correct

2024-09-04 10:36 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Leave_Clan">"Sair deste Clã"</string>
Previous translation was correct (based on English)

2024-09-04 10:36 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Clan_Uploads">"Skins Do Clã Enviadas"</string>
Lines 732 and 733: Previous translations were correct

2024-09-04 10:36 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="WRITE_MAIL">ESCREVER E-MAIL</string>
Previous translation was correct

2024-09-04 10:36 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Message_Sent_">E-mail Enviado!</string>
Previous translation was correct

2024-09-04 10:36 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Failed_to_send_mail_">Falha ao enviar o e-mail.</string>
Previous translation was correct

2024-09-04 10:41 UTC, Jeii20 commented
PR closed. Too many invalid changes. You tried to correct what was already correct at lines 71, 72,  77, 292, 381, 454, 455, 474, 569, 732, 733, 767, 774 and 783.

2024-09-04 10:41 UTC, closed without merging