Update strings.xml
simplicialsoftware/nebulous-translations pull request #574
Opened 2024-09-04 15:16 UTC by hassanekn

ID: 30886696

2024-09-04 15:25 UTC, Jeii20 requested changes

2024-09-04 15:25 UTC, Jeii20 commented on res/values-ar/strings.xml
> +    <string name="x4_Clan_XP_1_Day">4x نقاط خبرة العشيرة لمُدَّة يوم</string>   <string name="CHARGE_UP">الشُحنْةُ</string>
What happened here?

2024-09-04 15:31 UTC, hassanekn commented
Nothing happened, this happened by mistake

في الأربعاء، ٤ سبتمبر ٢٠٢٤, ٦:٢٥ م Jeii20 ***@***.***> كتب:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In res/values-ar/strings.xml
> <https://github.com/simplicialsoftware/nebulous-translations/pull/574#discussion_r1744004181>
> :
>
> > @@ -1272,8 +1272,7 @@
>      <string name="You_cannot_play_for_x_minutes_">لاتستطيع اللعب لمُدَّة %d دقيقة.</string>
>      <string name="x4_Clan_XP_Perm">4x نقاط خبرة عشيرة دائم!</string>
>      <string name="x4_Clan_XP_7_days">4x نقاط خبرة العشيرة لمُدَّة 7 ايَّام.</string>
> -    <string name="x4_Clan_XP_1_Day">4x نقاط خبرة العشيرة لمُدَّة يوم</string>
> -    <string name="CHARGE_UP">الشُحنْةُ</string>
> +    <string name="x4_Clan_XP_1_Day">4x نقاط خبرة العشيرة لمُدَّة يوم</string>   <string name="CHARGE_UP">الشُحنْةُ</string>
>
> What happened here?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/simplicialsoftware/nebulous-translations/pull/574#pullrequestreview-2280565674>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BK2ONCN2O2ZZF4PEE3WWVSDZU4Q65AVCNFSM6AAAAABNUR4ASWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOBQGU3DKNRXGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> <simplicialsoftware/nebulous-translations/pull/574/review/2280565674@
> github.com>
>

2024-09-04 15:47 UTC, Jeii20 commented
Then could you please fix it? All you need to do is to make a line break for the next `<string>`, just like it was before + perfectly aligned with the others. @hassanekn

2024-09-04 16:08 UTC, Jeii20 commented
It still keeps:

![Screenshot_20240904_130809_GitHub.jpg](https://github.com/user-attachments/assets/ec37e848-38c3-4e72-a8cf-1c65b4c3c8b6)

![Screenshot_20240904_130758_GitHub.jpg](https://github.com/user-attachments/assets/5211ccac-bc1d-4bc5-bcaa-00117f5b5e3f)

2024-09-04 16:29 UTC, hassanekn commented
It should be fixed now.

في الأربعاء، ٤ سبتمبر ٢٠٢٤, ٧:٠٨ م Jeii20 ***@***.***> كتب:

> It still keeps:
>
> Screenshot_20240904_130809_GitHub.jpg (view on web)
> <https://github.com/user-attachments/assets/ec37e848-38c3-4e72-a8cf-1c65b4c3c8b6>
>
> Screenshot_20240904_130758_GitHub.jpg (view on web)
> <https://github.com/user-attachments/assets/5211ccac-bc1d-4bc5-bcaa-00117f5b5e3f>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/simplicialsoftware/nebulous-translations/pull/574#issuecomment-2329468907>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BK2ONCIRRE6UBDQRYWCGJ2DZU4WBFAVCNFSM6AAAAABNUR4ASWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRZGQ3DQOJQG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-04 18:55 UTC, Jeii20 approved these changes
Perfect, thanks for your time. ^^
Already approved, can merge into main as soon as possible.

2024-09-04 19:26 UTC, hassanekn commented
You're welcome!

في الأربعاء، ٤ سبتمبر ٢٠٢٤, ٩:٥٥ م Jeii20 ***@***.***> كتب:

> ***@***.**** approved this pull request.
>
> Perfect, thanks for your time. ^^
> Already approved, can merge into main as soon as possible.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/simplicialsoftware/nebulous-translations/pull/574#pullrequestreview-2281012157>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BK2ONCLOCFDJ65SNBS2L6VTZU5JR7AVCNFSM6AAAAABNUR4ASWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOBRGAYTEMJVG4>
> .
> You are receiving this because you were mentioned.Message ID:
> <simplicialsoftware/nebulous-translations/pull/574/review/2281012157@
> github.com>
>

2024-09-05 08:25 UTC, hassanekn commented
Sorry but how can I merge it

في الأربعاء، ٤ سبتمبر ٢٠٢٤, ١٠:٢٦ م حسن آل برناوي ***@***.***>
كتب:

> You're welcome!
>
> في الأربعاء، ٤ سبتمبر ٢٠٢٤, ٩:٥٥ م Jeii20 ***@***.***> كتب:
>
>> ***@***.**** approved this pull request.
>>
>> Perfect, thanks for your time. ^^
>> Already approved, can merge into main as soon as possible.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/simplicialsoftware/nebulous-translations/pull/574#pullrequestreview-2281012157>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BK2ONCLOCFDJ65SNBS2L6VTZU5JR7AVCNFSM6AAAAABNUR4ASWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOBRGAYTEMJVG4>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> <simplicialsoftware/nebulous-translations/pull/574/review/2281012157@
>> github.com>
>>
>

2024-09-08 16:58 UTC, closed without merging