Ukraine translation improvement
simplicialsoftware/nebulous-translations pull request #608
Opened 2024-09-06 19:47 UTC by Limsoohyeon

Game ID 17187381

2024-09-06 20:23 UTC, Jeii20 requested changes

2024-09-06 20:23 UTC, Jeii20 commented on res/values-uk/strings.xml
> +    <string name="clan_id">ІДЕНТИФІКАТОР КЛАНУ</string>
Too long string length + too literal translation. Please change "ІДЕНТИФІКАТОР" to simply "ID".

2024-09-06 20:24 UTC, Jeii20 commented
**Council:** Try not to keep the string length too long for those like you did with `clan_id`. Also, please never use auto-translators (such as provided by Google Translator, DeepL, ChatGPT, Microsoft Translator etc), because it's part of the rules.

2024-09-07 10:15 UTC, Majaaaa1 commented
@Limsoohyeon hi this translation is not valid, there are errors due of the translator, please, if you are not sure,keep your native language.

2024-09-07 10:47 UTC, closed without merging