Update strings.xml
simplicialsoftware/nebulous-translations pull request #649
Opened 2024-09-08 21:05 UTC by Taki3600

The word(البشرة) It was translated by Google and this is not true 
The more correct word is الجلد

2024-09-08 21:16 UTC, Jeii20 approved these changes
Approved the changes, can merge into main as soon as possible.

2024-09-09 01:06 UTC, mody515 commented
> The word(البشرة) It was translated by Google and this is not true
> The more correct word is الجلد

نراك الشهر المقبل 😂

2024-09-10 01:21 UTC, Jeii20 requested changes

2024-09-10 01:21 UTC, Jeii20 commented on res/values-ar/strings.xml
> +    <string name="Set_Skin">وضع الجلد/string>
Could you please replace the `<` you removed here?

2024-09-25 13:23 UTC, closed without merging