Update language Arabic
simplicialsoftware/nebulous-translations pull request #686
Opened 2024-09-10 12:03 UTC by 5400169

I have modified some letters that change the pronunciation of the word

ID : 5400169

2024-09-13 19:48 UTC, ikrzz approved these changes

2024-09-20 08:08 UTC, W0O13 commented
previous word is ✅ انتصارات
new word is ❌ إنتصارات

The rest are ✅

2024-09-25 13:29 UTC, Jeii20 requested changes

2024-09-25 13:29 UTC, Jeii20 commented on res/values-ar/strings.xml
> +    <string name="Wins">"إنتصارات"</string>
Please make the requested change by a native speaker before approval.

2024-10-05 17:33 UTC, Jeii20 commented
PR closed. Unresolved conversations for too long time.

2024-10-05 17:33 UTC, closed without merging