Update Portuguese br language
simplicialsoftware/nebulous-translations pull request #733
Opened 2024-09-12 17:16 UTC by Gokushelby

No XML usado para recursos de string em aplicativos Android, as aspas ao redor dos valores dentro das tags <item> não são necessárias e, de fato, podem causar problemas. As strings são definidas diretamente como texto dentro das tags <item>, e a inclusão de aspas pode ser interpretada literalmente, o que não é a intenção. 
    O padrão do XML para Android não exige aspas ao redor dos valores das strings, e seguir essa convenção ajuda a evitar erros de processamento e garante a compatibilidade com as ferramentas de desenvolvimento e execução.

2024-09-12 17:17 UTC, Gokushelby commented
My ID in game:15490932

2024-09-12 18:03 UTC, Jeii20 approved these changes
Nice argument.
Approved the changes, can merge into main as soon as possible.

2024-09-25 13:07 UTC, Jeii20 requested changes

2024-09-25 13:07 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Quarter_Finals">Quartas de Final</string>
Please keep it as "Finais", because the previous text was already based on english text and, consequently, was already correct.

2024-09-25 13:07 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Delete_ALL_Messages_">Excluir Todas as Mensagens!</string>
Please do not remove all the capital letters here, because it's based on english value.

2024-09-25 13:07 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Mission_d_Failed">Missão %d Falhou!</string>
"Falhada" sounds better.

2024-10-05 16:28 UTC, Jeii20 commented
PR closed. Unresolved conversations for too long time.

2024-10-05 16:28 UTC, closed without merging