Update Portuguese br language
simplicialsoftware/nebulous-translations pull request #777
Opened 2024-09-16 14:53 UTC by Gokushelby

"Plasma Ganhado" – Pode ser mais claro como "Plasma Ganho" (usando o termo no particípio passado de forma mais natural).

Uma alternativa mais comun seria "Cancelar Inscrição"

2024-09-16 14:54 UTC, Gokushelby commented
My ID in game:15490932

2024-09-16 17:23 UTC, Jeii20 requested changes

2024-09-16 17:23 UTC, Jeii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Unregister">Cancelar Inscrição</string>
If you are trying to change for "Register" or "Unregister", this needs to be applied for every other line that contains the same text. Actually people who play tournaments are already used to "Registro", so please keep it as it was.

2024-09-26 10:05 UTC, Jeii20 commented
PR closed. Unresolved conversation(s) for too long time.

2024-09-26 10:05 UTC, closed without merging