values-es
simplicialsoftware/nebulous-translations pull request #782
Opened 2024-09-17 16:03 UTC by Banned44nebu

Traduções dos comandos do Nebulous.io

2024-09-17 20:09 UTC, Jeii20 commented
@CritiKangel please check this when you can

2024-09-18 16:56 UTC, CritiKangel requested changes

2024-09-18 16:56 UTC, CritiKangel commented on res/values-es/strings.xml
> +!welcome {mensaje Bienvenidos}
Inconsistency using brackets.

2024-09-18 16:56 UTC, CritiKangel commented on res/values-es/strings.xml
> +!welcome {mensaje Bienvenidos}
Traducción correcta: Mensaje de bienvenida

2024-09-18 16:56 UTC, CritiKangel commented on res/values-es/strings.xml
> +!slowchat (Alternar chat lento)
Traducción correcta: Ralentizar chat

2024-09-18 16:56 UTC, CritiKangel commented on res/values-es/strings.xml
> +!allow {id} (Dar permiso a un jugador)
Traducción adaptada: Permitir un jugador en la sala

2024-09-18 16:56 UTC, CritiKangel commented on res/values-es/strings.xml
> +!allow reset (Conceder permiso a un jugador)
Traducción correcta: Reiniciar permisos de jugadores en la sala.

2024-09-18 16:56 UTC, CritiKangel commented on res/values-es/strings.xml
> +!winner (Ganar una partida con tiempo)
Traducción correcta: Ganador de una partida con tiempo o por equipos.

2024-09-18 16:57 UTC, CritiKangel commented
@Banned44nebu No traduzcas un idioma que no hablas con fluidez, por favor.

2024-09-25 12:57 UTC, closed without merging