Indonesian Language Repair Update strings.xml
simplicialsoftware/nebulous-translations pull request #874
Opened 2024-10-14 04:04 UTC by TakaeSlept

Wrong Grammar

2024-10-14 04:05 UTC, TakaeSlept commented
Signed off by accident, when i commit it gets signed off automatically

2024-10-14 05:05 UTC, closed without merging

2024-10-16 20:13 UTC, Jeiii20 requested changes

2024-10-16 20:13 UTC, Jeiii20 commented on res/values-in/strings.xml
> +    <string name="US_West">"Amerika Barat"</string>
Wrong changes.

`US_East`: It should keep as "Amerika Tengah".
`US_West`: It should keep as "Amerika Utara.

You literally inverted and returned the old names. Those should not base off on the string name (in blue colour). Please return them as they were.

2024-10-16 20:13 UTC, Jeiii20 commented on res/values-in/strings.xml
> +    <string name="XP_">"Pengalaman:"</string>
"XP" is used everywhere. Should not be changed.

2024-10-16 20:13 UTC, Jeiii20 commented on res/values-in/strings.xml
> +    <string name="Clan_XP">"Pengalaman Klan"</string>
Same issue as line 87.