Update linguage português br
simplicialsoftware/nebulous-translations pull request #882
Opened 2024-10-17 00:05 UTC by Lauro48585995

Adicionado algumas pontuações e palavras em alguns trechos

Id:3147928 para tag de tradutor no jogo

2024-10-17 00:20 UTC, Lauro48585995 reviewed
String 793 erro grave aí

2024-10-17 00:27 UTC, Jeiii20 requested changes
Lines 699 (`join_clan_war`) and 702 (`banned_until`) don't need any punctuation, please fix it.

2024-10-17 00:34 UTC, Jeiii20 commented
**Another note:** Don't forget to always explain why the previous text was incorrect. Take this example:

Line 793 (`Survive_a_Zombie_Apocalypse`) is incorrect because, according to ChatGPT's research:

**The grammatically correct translation is "Sobreviva a um Apocalipse Zumbi".

In Portuguese, the verb "sobreviver" requires the preposition "a" when followed by a noun. Therefore, "Sobreviva a um Apocalipse Zumbi" is correct, while "Sobreviva um Apocalipse Zumbi" would be ungrammatical because it omits the necessary preposition.

Even though the first one is more literal, the second option is more appropriate for correct usage in Portuguese.**

Please consider this topic for your next changes. Thanks for your report. ^^

2024-10-17 00:58 UTC, Lauro48585995 reviewed
Id3147928 para tag

2024-10-17 09:38 UTC, Jeiii20 commented
@Lauro48585995 

Please stop messing up too much with the changes. Please undo these changes so them can be elligible. You can check what you did and return as they were.

2024-10-17 10:29 UTC, Jeiii20 requested changes

2024-10-17 10:29 UTC, Jeiii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="join_clan_war">"Entrar em Guerra de Clãs."</string>
```suggestion
    <string name="join_clan_war">"Entrar em Guerra de Clãs"</string>

2024-10-17 10:29 UTC, Jeiii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="banned_until">"Banido até. "</string>
```suggestion
    <string name="banned_until">"Banido até: "</string>

2024-10-17 10:29 UTC, Jeiii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Already_Blocked">Você Já Bloqueou!</string>
```suggestion
    <string name="Already_Blocked">Você Já Bloqueou</string>

2024-10-17 10:29 UTC, Jeiii20 commented on res/values-pt-rBR/strings.xml
> +3. Não tente se passar por um Moderador ou Youtuber. Isso fará com que você seja banido permanente.\n
```suggestion
1. Não compartilhe ou negocie contas com ninguém. Isso fará com que ambos os jogadores sejam banidos permanentemente.\n
2. Não peça contas de ninguém. Isso fará com que você seja banido permanentemente.\n
3. Não tente se passar por um Moderador ou Youtuber. Isso fará com que você seja banido permanentemente.\n

2024-10-17 10:29 UTC, Jeiii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="MARK_UNREAD">MARCAR COMO NÃO LIDA.</string>
```suggestion
    <string name="MARK_UNREAD">MARCAR COMO NÃO LIDA</string>

2024-10-17 10:29 UTC, Jeiii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Failed">Falhou!</string>
```suggestion
    <string name="Failed">Falhou</string>

2024-10-17 10:29 UTC, Jeiii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Sent_request_not_invited_">Pedido enviado! (não convidado).</string>
```suggestion
    <string name="Sent_request_not_invited_">Pedido enviado (você não foi convidado).</string>

2024-10-17 10:29 UTC, Jeiii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="team_warning">A parceria com um jogador que não está na sua equipe resultará em um banimento,Se você ver outras pessoas se unindo em outras equipes, poderá votar para expulsá-la da
Please return from comma to exclamation mark on where you changed.

2024-10-17 10:29 UTC, Jeiii20 commented on res/values-pt-rBR/strings.xml
> +        "A sua skin não foi aprovada! Aqui estão algumas das razões mais comuns. Você NÃO deve enviar:
Please return from exclamation mark to dot (period).

2024-10-17 10:29 UTC, Jeiii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="delete_prompt">Você tem certeza que quer excluir sua conta? Esta ação é PERMANENTE e NÃO PODERÁ SER DESFEITA.</string>
Please return from period to exclamation mark.

2024-10-17 11:33 UTC, Jeiii20 commented on res/values-pt-rBR/strings.xml
> +    <string name="Complete_campaign_mission_">Complete a missão de campanha.</string>
Same as line 699

```suggestion
    <string name="Complete_campaign_mission_">Complete a missão de campanha</string>

2024-10-21 10:50 UTC, Jeiii20 commented
PR closed. Too many inaccuracies regarding punctuations and unresolved conversations.

2024-10-21 10:50 UTC, closed without merging